name: StaffMode
author: ItsMax123
main: Max\StaffMode\Main
version: 2.1.1
api: [3.0.0]

commands:
 staffmode:
  description: Puts you in staff mode.
  usage: "/staffmode"
  aliases: ["sm"]
  permission: staffmode.command.staffmode
 staffchat:
    description: Puts you in staff chat.
    usage: "/staffchat"
    aliases: [ "sc" ]
    permission: staffmode.command.staffchat

permissions:

  staffmode.bypass:
    default: op
    description: Allows usage of staffmode tools against other staff members.

  staffmode.*:
    default: op
    description: Allows usage of all staffmode features.
    children:

      staffmode.silent:
        default: op
        description: Allows user to join and leave the server with no broadcasted message.

      staffmode.alerts:
        default: op
        description: Allows staff to receive alert when reported/BOLOED player joins the server.

      staffmode.command.staffmode:
        default: op
        description: Allows usage of the "/staffmode" command.

      staffmode.command.staffchat:
        default: op
        description: Allows usage of the "/staffchat" command.

      staffmode.tools.teleport:
        default: op
        description: Allows usage of the teleportation tool (compass) in staffmode.

      staffmode.tools.inventorymanager:
        default: op
        description: Allows usage of the InventoryManager tool (chest) in staffmode.
        children:
          staffmode.tools.inventorymanager.invspy:
            default: op
            description: Allows usage of the Inventory Spy (sub-tool of InventoryManager tool) in staffmode.
          staffmode.tools.inventorymanager.enderchestspy:
            default: op
            description: Allows usage of the EnderChest Spy (sub-tool of InventoryManager tool) in staffmode.
          staffmode.tools.inventorymanager.invclear:
            default: op
            description: Allows usage of the Inventory Clear (sub-tool of InventoryManager tool) in staffmode.
          staffmode.tools.inventorymanager.enderchestclear:
            default: op
            description: Allows usage of the EnderChest Clear (sub-tool of InventoryManager tool) in staffmode.

      staffmode.tools.freeze:
        default: op
        description: Allows usage of the freezing tool (ice block) in staffmode.

      staffmode.tools.kick:
        default: op
        description: Allows usage of the kicking tool (gold sword) in staffmode.

      staffmode.tools.exit:
        default: true
        description: Allows usage of the exit tool (redstone torch) in staffmode.
